/**
 * Hardcoded sample data served to LOGGED-OUT visitors only.
 *
 * This module is the ONLY source of preview data shown to guests. The
 * server has zero knowledge of sample data — a CHECK constraint rejects
 * any row with source='sample' at insert time. Keeping the preview
 * entirely client-side makes it impossible for sample rows to ever leak
 * into a real user's account.
 *
 * Pages use these arrays via `useGuestPreview()` — when !isLoggedIn,
 * the page renders from the array instead of calling the API. When the
 * user signs in, the page falls back to real queries.
 */

import type {
  TraceListItem,
  TraceDetail,
  EventsByFeature,
  EventsByCustomer,
  EventsByModel,
  ObserveEvent,
  ModelSummary,
  Customer,
} from "@/lib/api";

const ISO = (offsetMinutes: number) =>
  new Date(Date.now() - offsetMinutes * 60_000).toISOString();

export const GUEST_EVENTS_BY_FEATURE: EventsByFeature[] = [
  {
    feature_key: "rag_query",
    event_count: 1247,
    total_cost: 52.43,
    total_revenue: 189.5,
    total_usage: 1247,
    margin_pct: 72,
    last_seen: ISO(5),
  },
  {
    feature_key: "code_review_agent",
    event_count: 318,
    total_cost: 48.11,
    total_revenue: 120.0,
    total_usage: 318,
    margin_pct: 60,
    last_seen: ISO(12),
  },
  {
    feature_key: "content_pipeline",
    event_count: 892,
    total_cost: 31.2,
    total_revenue: 76.6,
    total_usage: 892,
    margin_pct: 59,
    last_seen: ISO(22),
  },
  {
    feature_key: "document_extraction",
    event_count: 2104,
    total_cost: 19.8,
    total_revenue: 42.3,
    total_usage: 2104,
    margin_pct: 53,
    last_seen: ISO(41),
  },
  {
    feature_key: "semantic_search",
    event_count: 5820,
    total_cost: 12.4,
    total_revenue: 16.1,
    total_usage: 5820,
    margin_pct: 23,
    last_seen: ISO(3),
  },
  {
    feature_key: "email_draft",
    event_count: 412,
    total_cost: 14.0,
    total_revenue: 8.2,
    total_usage: 412,
    margin_pct: -71,
    last_seen: ISO(8),
  },
];

export const GUEST_EVENTS_BY_CUSTOMER: EventsByCustomer[] = [
  {
    customer_id: "cus_acme",
    customer_name: "Acme Corp",
    event_count: 4201,
    total_cost: 62.4,
    total_revenue: 199.0,
    margin_pct: 68,
    last_seen: ISO(4),
  },
  {
    customer_id: "cus_tidewater",
    customer_name: "Tidewater AI",
    event_count: 2810,
    total_cost: 48.2,
    total_revenue: 149.0,
    margin_pct: 68,
    last_seen: ISO(9),
  },
  {
    customer_id: "cus_neondata",
    customer_name: "NeonData",
    event_count: 1902,
    total_cost: 41.0,
    total_revenue: 89.0,
    margin_pct: 54,
    last_seen: ISO(16),
  },
  {
    customer_id: "cus_circleops",
    customer_name: "CircleOps",
    event_count: 640,
    total_cost: 18.3,
    total_revenue: 29.0,
    margin_pct: 37,
    last_seen: ISO(31),
  },
  {
    customer_id: "cus_blazeml",
    customer_name: "BlazeML",
    event_count: 410,
    total_cost: 22.0,
    total_revenue: 9.0,
    margin_pct: -144,
    last_seen: ISO(48),
  },
];

export const GUEST_EVENTS_BY_MODEL: EventsByModel[] = [
  {
    model: "gpt-4o",
    model_provider: "openai",
    event_count: 2104,
    total_cost: 96.3,
    total_revenue: 280.0,
    total_usage: 612_400,
    margin_pct: 65,
    last_seen: ISO(2),
  },
  {
    model: "gpt-4o-mini",
    model_provider: "openai",
    event_count: 8902,
    total_cost: 18.7,
    total_revenue: 82.0,
    total_usage: 2_180_500,
    margin_pct: 77,
    last_seen: ISO(1),
  },
  {
    model: "claude-3-5-sonnet",
    model_provider: "anthropic",
    event_count: 1320,
    total_cost: 44.0,
    total_revenue: 110.0,
    total_usage: 410_200,
    margin_pct: 60,
    last_seen: ISO(6),
  },
  {
    model: "text-embedding-3-small",
    model_provider: "openai",
    event_count: 5820,
    total_cost: 3.4,
    total_revenue: 16.0,
    total_usage: 11_640_000,
    margin_pct: 79,
    last_seen: ISO(4),
  },
];

export const GUEST_TRACES: TraceListItem[] = [
  {
    trace_id: "sample-trace-rag-pipeline",
    start_time: new Date(Date.now() - 1 * 3600_000).toISOString(),
    span_count: 5,
    total_cost: 0.423,
    total_revenue: 1.2,
    total_duration_ms: 3200,
    root_event: "rag_query",
    cost_types: ["llm", "embedding", "vector_db"],
  },
  {
    trace_id: "sample-trace-content-gen",
    start_time: new Date(Date.now() - 4 * 3600_000).toISOString(),
    span_count: 4,
    total_cost: 0.85,
    total_revenue: 2.0,
    total_duration_ms: 5800,
    root_event: "content_pipeline",
    cost_types: ["llm", "compute", "api"],
  },
  {
    trace_id: "sample-trace-code-review",
    start_time: new Date(Date.now() - 8 * 3600_000).toISOString(),
    span_count: 6,
    total_cost: 1.32,
    total_revenue: 3.5,
    total_duration_ms: 12400,
    root_event: "code_review_agent",
    cost_types: ["llm", "compute", "database", "api"],
  },
  {
    trace_id: "sample-trace-data-extract",
    start_time: new Date(Date.now() - 12 * 3600_000).toISOString(),
    span_count: 3,
    total_cost: 0.18,
    total_revenue: 0.5,
    total_duration_ms: 2100,
    root_event: "document_extraction",
    cost_types: ["llm", "compute"],
  },
  {
    trace_id: "sample-trace-search",
    start_time: new Date(Date.now() - 18 * 3600_000).toISOString(),
    span_count: 4,
    total_cost: 0.065,
    total_revenue: 0.2,
    total_duration_ms: 890,
    root_event: "semantic_search",
    cost_types: ["embedding", "vector_db"],
  },
];

const SAMPLE_TRACE_DETAILS: Record<string, TraceDetail> = {
  "sample-trace-rag-pipeline": {
    trace_id: "sample-trace-rag-pipeline",
    spans: [
      {
        id: 1,
        user_id: "guest",
        customer_id: "cus_acme",
        feature_key: "rag_query",
        event_name: "rag_query",
        timestamp: new Date(Date.now() - 3600_000).toISOString(),
        cost_amount: 0.08,
        cost_unit: "usd",
        revenue_amount: 0.4,
        usage_units: 2400,
        source: "sample",
        model: "gpt-4o-mini",
        model_provider: "openai",
        span_id: "s1",
        parent_span_id: null,
        duration_ms: 520,
        cost_type: "llm",
      } as unknown as TraceDetail["spans"][number],
      {
        id: 2,
        user_id: "guest",
        customer_id: "cus_acme",
        feature_key: "rag_query",
        event_name: "embed_query",
        timestamp: new Date(Date.now() - 3600_000 + 300).toISOString(),
        cost_amount: 0.002,
        cost_unit: "usd",
        revenue_amount: 0,
        usage_units: 64,
        source: "sample",
        model: "text-embedding-3-small",
        model_provider: "openai",
        span_id: "s2",
        parent_span_id: "s1",
        duration_ms: 90,
        cost_type: "embedding",
      } as unknown as TraceDetail["spans"][number],
      {
        id: 3,
        user_id: "guest",
        customer_id: "cus_acme",
        feature_key: "rag_query",
        event_name: "vector_search",
        timestamp: new Date(Date.now() - 3600_000 + 450).toISOString(),
        cost_amount: 0.003,
        cost_unit: "usd",
        revenue_amount: 0,
        usage_units: 8,
        source: "sample",
        model: null,
        model_provider: null,
        span_id: "s3",
        parent_span_id: "s1",
        duration_ms: 180,
        cost_type: "vector_db",
      } as unknown as TraceDetail["spans"][number],
      {
        id: 4,
        user_id: "guest",
        customer_id: "cus_acme",
        feature_key: "rag_query",
        event_name: "generate_answer",
        timestamp: new Date(Date.now() - 3600_000 + 700).toISOString(),
        cost_amount: 0.33,
        cost_unit: "usd",
        revenue_amount: 0.8,
        usage_units: 5200,
        source: "sample",
        model: "gpt-4o",
        model_provider: "openai",
        span_id: "s4",
        parent_span_id: "s1",
        duration_ms: 2100,
        cost_type: "llm",
      } as unknown as TraceDetail["spans"][number],
      {
        id: 5,
        user_id: "guest",
        customer_id: "cus_acme",
        feature_key: "rag_query",
        event_name: "rerank_results",
        timestamp: new Date(Date.now() - 3600_000 + 900).toISOString(),
        cost_amount: 0.008,
        cost_unit: "usd",
        revenue_amount: 0,
        usage_units: 320,
        source: "sample",
        model: "gpt-4o-mini",
        model_provider: "openai",
        span_id: "s5",
        parent_span_id: "s1",
        duration_ms: 310,
        cost_type: "llm",
      } as unknown as TraceDetail["spans"][number],
    ],
  },
};

export function getGuestTraceDetail(traceId: string): TraceDetail | null {
  return SAMPLE_TRACE_DETAILS[traceId] ?? null;
}

export const GUEST_EVENTS: ObserveEvent[] = Array.from({ length: 20 }, (_, i) => {
  const features = [
    "rag_query",
    "code_review_agent",
    "content_pipeline",
    "document_extraction",
    "semantic_search",
    "email_draft",
  ];
  const customers = [
    ["cus_acme", "Acme Corp"],
    ["cus_tidewater", "Tidewater AI"],
    ["cus_neondata", "NeonData"],
    ["cus_circleops", "CircleOps"],
    ["cus_blazeml", "BlazeML"],
  ];
  const models: Array<[string, string]> = [
    ["gpt-4o", "openai"],
    ["gpt-4o-mini", "openai"],
    ["claude-3-5-sonnet", "anthropic"],
    ["text-embedding-3-small", "openai"],
  ];
  const feature = features[i % features.length];
  const [cid, cname] = customers[i % customers.length];
  const [model, provider] = models[i % models.length];
  const cost = Number((0.002 + Math.random() * 0.28).toFixed(4));
  return {
    id: 1000 + i,
    user_id: "guest",
    customer_id: cid,
    customer_name: cname,
    feature_key: feature,
    event_name: feature,
    timestamp: ISO(i * 7),
    cost_amount: cost,
    cost_unit: "usd",
    revenue_amount: Number((cost * (1 + Math.random() * 2)).toFixed(4)),
    usage_units: Math.floor(200 + Math.random() * 1800),
    model,
    model_provider: provider,
    source: "sample",
    granularity: "event",
    is_inferred: false,
    properties: null,
    created_at: ISO(i * 7),
    trace_id: null,
    span_id: null,
    parent_span_id: null,
    duration_ms: Math.floor(120 + Math.random() * 1800),
    cost_type: model.startsWith("text-embedding") ? "embedding" : "llm",
  };
});

export const GUEST_MODELS: ModelSummary[] = [
  {
    model: "gpt-4o",
    model_provider: "openai",
    event_count: 2104,
    customer_count: 5,
    feature_count: 6,
    total_cost: 96.3,
    total_revenue: 280.0,
    total_usage: 612_400,
    avg_cost_per_event: 0.0458,
    margin_pct: 65,
    last_seen: ISO(2),
  },
  {
    model: "gpt-4o-mini",
    model_provider: "openai",
    event_count: 8902,
    customer_count: 5,
    feature_count: 6,
    total_cost: 18.7,
    total_revenue: 82.0,
    total_usage: 2_180_500,
    avg_cost_per_event: 0.0021,
    margin_pct: 77,
    last_seen: ISO(1),
  },
  {
    model: "claude-3-5-sonnet",
    model_provider: "anthropic",
    event_count: 1320,
    customer_count: 3,
    feature_count: 3,
    total_cost: 44.0,
    total_revenue: 110.0,
    total_usage: 410_200,
    avg_cost_per_event: 0.0333,
    margin_pct: 60,
    last_seen: ISO(6),
  },
  {
    model: "text-embedding-3-small",
    model_provider: "openai",
    event_count: 5820,
    customer_count: 4,
    feature_count: 2,
    total_cost: 3.4,
    total_revenue: 16.0,
    total_usage: 11_640_000,
    avg_cost_per_event: 0.00058,
    margin_pct: 79,
    last_seen: ISO(4),
  },
];

export const GUEST_CUSTOMERS: Customer[] = [
  {
    id: "cus_acme",
    customer_id: "cus_acme",
    name: "Acme Corp",
    email: "ops@acme.example",
    segment: "enterprise",
    created_at: new Date(Date.now() - 180 * 86_400_000).toISOString(),
  },
  {
    id: "cus_tidewater",
    customer_id: "cus_tidewater",
    name: "Tidewater AI",
    email: "hello@tidewater.example",
    segment: "growth",
    created_at: new Date(Date.now() - 120 * 86_400_000).toISOString(),
  },
  {
    id: "cus_neondata",
    customer_id: "cus_neondata",
    name: "NeonData",
    email: "team@neondata.example",
    segment: "growth",
    created_at: new Date(Date.now() - 90 * 86_400_000).toISOString(),
  },
  {
    id: "cus_circleops",
    customer_id: "cus_circleops",
    name: "CircleOps",
    email: "accounts@circleops.example",
    segment: "starter",
    created_at: new Date(Date.now() - 60 * 86_400_000).toISOString(),
  },
  {
    id: "cus_blazeml",
    customer_id: "cus_blazeml",
    name: "BlazeML",
    email: "hello@blazeml.example",
    segment: "starter",
    created_at: new Date(Date.now() - 30 * 86_400_000).toISOString(),
  },
];
