import type { Simulation } from '@/types/simulation'

export function getSampleSimulations(userId: string): Simulation[] {
  return [
    {
      id: 'sim-001',
      user_id: userId,
      name: 'API Pricing Optimization',
      status: 'completed',
      segment_name: 'All Segments',
      scenarios: [
        {
          id: 'sc-001a',
          name: 'Conservative (+10%)',
          description: 'Moderate price increase across AI features',
          changes: [
            { feature_key: 'ai_summarization', change_type: 'percentage_increase', change_value: 10 },
            { feature_key: 'image_generation', change_type: 'percentage_increase', change_value: 10 },
          ],
          projected_revenue: 3.08,
          projected_cost: 1.29,
          projected_margin_pct: 58,
        },
        {
          id: 'sc-001b',
          name: 'Aggressive (+25%)',
          description: 'Larger price increase to improve margins',
          changes: [
            { feature_key: 'ai_summarization', change_type: 'percentage_increase', change_value: 25 },
            { feature_key: 'image_generation', change_type: 'percentage_increase', change_value: 25 },
          ],
          projected_revenue: 3.50,
          projected_cost: 1.29,
          projected_margin_pct: 63,
        },
      ],
      feature_analysis: [
        {
          feature_key: 'ai_summarization',
          current_cost: 0.82,
          current_revenue: 1.80,
          current_margin_pct: 54,
          projected_revenue: 2.25,
          projected_margin_pct: 64,
          margin_delta_pct: 10,
        },
        {
          feature_key: 'image_generation',
          current_cost: 0.14,
          current_revenue: 0.95,
          current_margin_pct: 85,
          projected_revenue: 1.19,
          projected_margin_pct: 88,
          margin_delta_pct: 3,
        },
        {
          feature_key: 'search',
          current_cost: 0.01,
          current_revenue: 0.045,
          current_margin_pct: 78,
          projected_revenue: 0.045,
          projected_margin_pct: 78,
          margin_delta_pct: 0,
        },
      ],
      customer_impacts: [
        {
          customer_id: 'cus_001',
          customer_name: 'Acme Corp',
          current_revenue: 1.10,
          projected_revenue: 1.38,
          revenue_delta: 0.28,
          revenue_delta_pct: 25,
          churn_risk: 'low',
          segment: 'Enterprise',
        },
        {
          customer_id: 'cus_002',
          customer_name: 'TechStart Inc',
          current_revenue: 0.45,
          projected_revenue: 0.56,
          revenue_delta: 0.11,
          revenue_delta_pct: 25,
          churn_risk: 'medium',
          segment: 'SMB',
        },
        {
          customer_id: 'cus_003',
          customer_name: 'Global Solutions',
          current_revenue: 0.60,
          projected_revenue: 0.75,
          revenue_delta: 0.15,
          revenue_delta_pct: 25,
          churn_risk: 'low',
          segment: 'Mid-Market',
        },
        {
          customer_id: 'cus_004',
          customer_name: 'Startup Labs',
          current_revenue: 0.15,
          projected_revenue: 0.19,
          revenue_delta: 0.04,
          revenue_delta_pct: 25,
          churn_risk: 'high',
          segment: 'SMB',
        },
        {
          customer_id: 'cus_005',
          customer_name: 'Enterprise Co',
          current_revenue: 0.20,
          projected_revenue: 0.25,
          revenue_delta: 0.05,
          revenue_delta_pct: 25,
          churn_risk: 'low',
          segment: 'Enterprise',
        },
      ],
      margin_impact: {
        current_margin_pct: 54,
        projected_margin_pct: 63,
        margin_delta_pct: 9,
        total_current_revenue: 2.80,
        total_projected_revenue: 3.50,
        total_cost: 1.29,
        customers_affected: 5,
        high_churn_risk_count: 1,
      },
      confidence_score: 78,
      key_insight: 'A 25% price increase on AI features would improve overall margin from 54% to 63%, with only 1 customer at high churn risk (Startup Labs, SMB segment).',
      winning_scenario_id: 'sc-001b',
      rolled_out_at: null,
      created_at: '2026-03-10T09:00:00Z',
      updated_at: '2026-03-10T09:05:00Z',
    },
    {
      id: 'sim-002',
      user_id: userId,
      name: 'Enterprise Tier Restructure',
      status: 'completed',
      segment_name: 'Enterprise',
      scenarios: [
        {
          id: 'sc-002a',
          name: 'Bundle AI features',
          description: 'Include AI summarization in enterprise tier at flat rate',
          changes: [
            { feature_key: 'ai_summarization', change_type: 'new_price', change_value: 0.40 },
          ],
          projected_revenue: 2.60,
          projected_cost: 1.29,
          projected_margin_pct: 50,
        },
        {
          id: 'sc-002b',
          name: 'Usage-based AI pricing',
          description: 'Move to per-unit pricing for AI features',
          changes: [
            { feature_key: 'ai_summarization', change_type: 'percentage_increase', change_value: 15 },
            { feature_key: 'search', change_type: 'percentage_increase', change_value: 50 },
          ],
          projected_revenue: 3.15,
          projected_cost: 1.29,
          projected_margin_pct: 59,
        },
        {
          id: 'sc-002c',
          name: 'Premium image tier',
          description: 'Increase image generation pricing for enterprise',
          changes: [
            { feature_key: 'image_generation', change_type: 'percentage_increase', change_value: 40 },
          ],
          projected_revenue: 3.18,
          projected_cost: 1.29,
          projected_margin_pct: 59,
        },
      ],
      feature_analysis: [
        {
          feature_key: 'ai_summarization',
          current_cost: 0.82,
          current_revenue: 1.80,
          current_margin_pct: 54,
          projected_revenue: 2.07,
          projected_margin_pct: 60,
          margin_delta_pct: 6,
        },
        {
          feature_key: 'image_generation',
          current_cost: 0.14,
          current_revenue: 0.95,
          current_margin_pct: 85,
          projected_revenue: 1.33,
          projected_margin_pct: 89,
          margin_delta_pct: 4,
        },
      ],
      customer_impacts: [
        {
          customer_id: 'cus_001',
          customer_name: 'Acme Corp',
          current_revenue: 1.10,
          projected_revenue: 1.32,
          revenue_delta: 0.22,
          revenue_delta_pct: 20,
          churn_risk: 'low',
          segment: 'Enterprise',
        },
        {
          customer_id: 'cus_005',
          customer_name: 'Enterprise Co',
          current_revenue: 0.20,
          projected_revenue: 0.28,
          revenue_delta: 0.08,
          revenue_delta_pct: 40,
          churn_risk: 'medium',
          segment: 'Enterprise',
        },
      ],
      margin_impact: {
        current_margin_pct: 54,
        projected_margin_pct: 59,
        margin_delta_pct: 5,
        total_current_revenue: 2.80,
        total_projected_revenue: 3.18,
        total_cost: 1.29,
        customers_affected: 2,
        high_churn_risk_count: 0,
      },
      confidence_score: 65,
      key_insight: 'Restructuring enterprise pricing with a premium image tier yields +5% margin improvement with no high churn risk customers.',
      winning_scenario_id: 'sc-002c',
      rolled_out_at: null,
      created_at: '2026-03-12T14:00:00Z',
      updated_at: '2026-03-12T14:08:00Z',
    },
    {
      id: 'sim-003',
      user_id: userId,
      name: 'Usage-Based Pricing Test',
      status: 'draft',
      scenarios: [
        {
          id: 'sc-003a',
          name: 'Per-token pricing',
          description: 'Charge per 1000 tokens across all AI features',
          changes: [
            { feature_key: 'ai_summarization', change_type: 'new_price', change_value: 0.03 },
            { feature_key: 'search', change_type: 'new_price', change_value: 0.005 },
          ],
        },
      ],
      feature_analysis: [],
      customer_impacts: [],
      margin_impact: null,
      confidence_score: null,
      key_insight: null,
      winning_scenario_id: null,
      rolled_out_at: null,
      created_at: '2026-03-15T11:00:00Z',
      updated_at: '2026-03-15T11:00:00Z',
    },
  ]
}
