blank_issues_enabled: true
contact_links:
  - name: Questions & Discussion
    url: https://github.com/tansohq/observe/discussions
    about: Ask questions, share ideas, or get help from the community
