name: Feature Request
description: Suggest a feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting an improvement to Observe.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What's the use case?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you've thought about.
    validations:
      required: false
